# Generated by Django 3.2.12 on 2022-03-05 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=35, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('districtid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100, verbose_name='district')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedbackid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('subject', models.CharField(max_length=50, verbose_name='subject')),
                ('feedback', models.CharField(max_length=250, verbose_name='feedback')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='punish.district')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('password', models.CharField(max_length=25, verbose_name='password')),
                ('role', models.CharField(max_length=25, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('repid', models.AutoField(primary_key=True, serialize=False)),
                ('rep', models.CharField(max_length=200, verbose_name='reply')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('phoneno', models.CharField(max_length=10, verbose_name='phoneno')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('aadharno', models.CharField(max_length=20, verbose_name='aadharno')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
                ('gender', models.CharField(max_length=20, verbose_name='gender')),
                ('photo', models.FileField(upload_to='img/', verbose_name='photo')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='punish.district')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='punish.location')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='punish.login')),
            ],
        ),
        migrations.CreateModel(
            name='police',
            fields=[
                ('policeid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('mobileno', models.CharField(max_length=20, verbose_name='mobileno')),
                ('aadharno', models.CharField(max_length=20, verbose_name='aadharno')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('qualification', models.CharField(max_length=30, verbose_name='qualification')),
                ('rewards', models.CharField(max_length=50, verbose_name='rewards')),
                ('dapartment', models.CharField(max_length=30, verbose_name='department')),
                ('designation', models.CharField(max_length=30, verbose_name='designation')),
                ('gender', models.CharField(max_length=20, verbose_name='gender')),
                ('date', models.CharField(max_length=30, verbose_name='date')),
                ('photo', models.FileField(upload_to='img/', verbose_name='photo')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='punish.district')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='punish.location')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='punish.login')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaintid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('phoneno', models.CharField(max_length=20, verbose_name='mobileno')),
                ('complaint', models.CharField(max_length=300, verbose_name='complaint')),
                ('time', models.CharField(max_length=50, verbose_name='time')),
                ('spot', models.CharField(max_length=50, verbose_name='spot')),
                ('evidence', models.FileField(upload_to='img/', verbose_name='evidence')),
                ('date', models.DateField(max_length=30, verbose_name='date')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='punish.category')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='punish.district')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='punish.location')),
            ],
        ),
    ]
