# Generated by Django 3.2.12 on 2022-03-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='district',
            field=models.CharField(default=1, max_length=30, verbose_name='district'),
            preserve_default=False,
        ),
    ]
