# Generated by Django 3.2.12 on 2022-03-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punish', '0002_login_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default=1, max_length=100, verbose_name='status:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(default=1, max_length=100, verbose_name='status:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='police',
            name='status',
            field=models.CharField(default=1, max_length=100, verbose_name='status:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default=1, max_length=100, verbose_name='status:'),
            preserve_default=False,
        ),
    ]
