# Generated by Django 3.2.12 on 2022-03-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punish', '0004_polcom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='district',
        ),
    ]
