# Generated by Django 3.2.12 on 2022-03-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('punish', '0005_remove_login_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='punish.login'),
        ),
    ]
