# Generated by Django 3.2.12 on 2022-03-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('punish', '0006_complaint_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='login',
        ),
        migrations.AddField(
            model_name='complaint',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='punish.user'),
        ),
    ]
