# Generated by Django 3.2.12 on 2022-03-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punish', '0007_auto_20220306_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='category',
            field=models.CharField(default=1, max_length=100, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.CharField(default=1, max_length=30, verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='username',
            field=models.CharField(default=1, max_length=200, verbose_name='username'),
            preserve_default=False,
        ),
    ]
